### ISSUE TITLE
Coga Suggested User Need: As a user with a cognitive or learning disability and who likes to browse on the Web, I need the structure to make sense to me, so that I find what I am looking for, without looking in the wrong place.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/ctaur#12]
Issue raised by COGA Task Force as summarized in Scott's message to the mailing list.

**Comment by jasonjgw** [comment]
This appears to be a general user need that is not specific to collaboration-related functionality. I would suggest either substituting a more specific requirement with suitable scope, or closing this issue as more appropriate for the user needs conversation in FAST.

**Comment by sehollier** [comment]
Agreed, no additional comment.

**Comment by davidofyork** [comment]
Relates to #13 #14 #15.
