### ISSUE TITLE
•	Coga Suggested  REQ (Requirement ) Allow the user to determine the storage location of the collaboration space.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/ctaur#13]
Comment from COGA Task Force via Scott's summary.

**Comment by jasonjgw** [comment]
It isn't clear what the accessibility-related need is that this proposal would satisfy. Also, it can be interpreted as requiring the application to (1) allow the user to find out where the content is stored, or (2) enable the user to select where the content is stored, or both.

I think this proposal needs clarification. Some applications won't have multiple options regarding storage locations. They'll simply store the content in their database.

**Comment by sehollier** [comment]
Many tools are limited by where the collaboration space is but have many different ways to access E.g. SharePoint/OneDrive can represent files in Browser, but also represent files as physical storage in file explorer in windows. As such, perhaps the accessibility aspects of this are already addressed as wherever the collaboration space is, there are multiple devices that can access it based on user need.
