### ISSUE TITLE
Coga Suggested REQ (Requirement): Allow the user to structure the collaboration space.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/ctaur#15]
Comment by COGA Task Force, via Scott's summary.

**Comment by jasonjgw** [comment]
It is unclear what this means, how it should be implemented in a multi-user application designed for collaboration, or how to specify the accessibility-specific rationale.

**Comment by sehollier** [comment]
Perhaps this is referring to simplified collaboration space to make it easier to understand. This was addressed in an earlier GitHub issue.
