### ISSUE TITLE
Coga Suggested  REQ (Requirement ) Provide  summaries of changes. Examples: list of comments and revisions they made (for use in meetings, for example). Also, items marked resolved: these can be difficult to track, understand how/why they were resolved.(From CTAUR with COGA 

### ISSUE THREAD

**Issue by jasonjgw** [w3c/ctaur#17]
COGA Task Force comment, via Scott's summary.

**Comment by jasonjgw** [comment]
In most revision control tools, a commit message can be entered to describe a change or set of related changes. Perhaps this would satisfy the proposed requirement.

Describing what the change does is not the same as summarizing content that was added or revised, however. It isn't clear whether this proposal is meant to cover either or both cases.

Interactive editors such as word processors generally do not have a "commit changes" function. Would we be requesting a feature enabling the author to attach a label (e.g., version number) to a revision, and create a change log entry for it? We would then need a feature permitting the user to review the change log entries.

Does Git already satisfy the proposed requirement?

**Comment by sehollier** [comment]
There seems to be two different aspects, one seems to be issue tracking as previously mentioned in other GitHub issues and the other is a separate list of document changes which as Jason noted, could have potential but could be difficult to implement.
