### ISSUE TITLE
Coga Suggested REQ (Requirement  : I need ability to mark for myself which items need you to follow up on. Notifications sometimes get marked "read" but do not have a way for you to remember to come back to them. You may need to review them multiple times to be sure you understand, and to complete the task. Further allow Users a view of just the items they need to follow up on, both from notifications, and any additional they identify.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/ctaur#19]
COGA Task Force comment, via Scott's summary.

**Comment by jasonjgw** [comment]
It isn't clear what "notifications" are intended here. For instance, comments and suggested changes in a document are not presented as notifications.

A collaborative editing tool could have integrated "chat" features that may, perhaps, produce notifications. In that case, there's an overlap with *RTC Accessibility User Requirements*, and it isn't clear what we should say here, if anything.

**Comment by jasonjgw** [comment]
If this is about issue tracking tools, then what would the requirement be? Assigning the issue to oneself "marks" it as needing follow-up. A label could be used for the same purpose. However, it might be desirable for the user to be able to designate an issue as needing further attention, but privately - the designation would not be visible to other users.

Thus, first, is this primarily about issue tracking, and second, does it require anything beyond what issue tracking tools already tend to provide?

**Comment by sehollier** [comment]
agreed, there sems to be a few GitHub issues that seem to talk about notifications but to my thinking keep coming back to issue tracker for notifications relating to general tool use.
