### ISSUE TITLE
Coga Suggested REQ (Requirement   Provide a mode of operation for a separate viewing mechanism. Example: different window. This can better support readability, and maintain focus in the main document.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/ctaur#20]
COGA Task Force comment, via Scott's summary.

**Comment by jasonjgw** [comment]
Does this mean: provide a view that shows only the content to be edited in a window, excluding the application's user interface? Would this view be read-only? Should it include annotations such as comments, or would this be user-configurable? Is some other implementation intended?

I assume the rationale would relate to user interface complexity, distractions, or both.

**Comment by sehollier** [comment]
Yes, assume this is to make the interface less complex and maybe helpful.

**Comment by JaninaSajka** [comment]
Accepted in the form of multiple views and API support
