### ISSUE TITLE
Coga Suggested REQ (Requirement  Ensure that users can choose how the notifications are delivered, such as through personalization and extensions.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/ctaur#21]
COGA Task Force comment, via Scott's summary.

**Comment by jasonjgw** [comment]
It isn't clear what "notifications" this refers to.

**Comment by sehollier** [comment]
I think this relates to the concept of the issue tracker as mentioned in an earlier Github issue.

**Comment by JaninaSajka** [comment]
Accepted
