### ISSUE TITLE
•	Add section about needing a wayfinding/orientation space within a collaboration tool. 

### ISSUE THREAD

**Issue by jasonjgw** [w3c/ctaur#22]
This helps users:

* Know where within the tool they are to complete certain tasks.
* The names and locations available within the tool used for a specific group. Example: if there are multiple document libraries within a collaboration space, this makes finding the one related to a project difficult to find.
* Review a summary of current work history on a project
* Upcoming important deadlines and tasks should also be available and easily found. This place needs to be:
* Persistent
* “One source of truth”

[COGA Task Force comment, via Scott's message.]

**Comment by jasonjgw** [comment]
It isn't clear how to describe the desired functionality in more concrete and specific terms. Perhaps it would be best to treat each of the points in the description as a separate requirement/issue. Some of them refer to the user interface of the tool, and others to the content, so separating them out would probably be the best approach.

**Comment by sehollier** [comment]
no additional comments from me.

**Comment by JaninaSajka** [comment]
Not CTAUR specific, though likely helpful in a complex enviornment generally.
