### ISSUE TITLE
Add section about improving participation of all members.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/ctaur#23]
Examples include:

* Identify when group members are not participating in conversations and decisions.
* They may not be able to use one or more of the methods.
* They may not know the conversations and decision making opportunities are taking place.
* Silence is not necessarily an indicator of agreement.

**Comment by jasonjgw** [comment]
This could relate to issue tracking, but it seems much more general. I would suggest rewriting this as a more focused issue with reference to the collaborative functionality which it would affect.

It is also unclear that tools themselves can address these concerns significantly. Isn't it the responsibility of the collaborating parties to provide an inclusive social environment? Reliably and automatically detecting non-participation would be difficult, for instance. If I read a draft, but I do not leave comments, am I participating? Even if there were a "no comments" button, I might not want to use it, especially if I plan to review the text later or to comment on a later version after waiting for others to make enhancements.

**Comment by sehollier** [comment]
Broadly agree but can see merit in expanding more accessible issue tracker.

**Comment by JaninaSajka** [comment]
Accepted in the form of the requirement to identify who's editing where. Note we cannot require to indicate what member of a team might not be participating. So our solution is a bit different from the phrasing in the issue.
