### ISSUE TITLE
Scope and definition of "collaboration tools", and associated comments.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/ctaur#24]
[Quoting from the COGA Task Force comment as submitted to the mailing list]:

I went through it… overall i’m unsure about the definition of collaboration tools frankly.
I think a call may be good.

I’d just add: 
• Microsoft Office 365, 
• Google Workspace  now to the list. 
We are really talking about the collaborative functionlity of these content creation tools ( For Documents,Presentations, spreadsheets, designs etc)

However it seems to me the definition  a "callaboration tool” these days is more like Miro, Trello, Slack, Jira, Asana,Canva. … do we want to go there?

But maybe not. … I think the wording should be changed to collaboration functionlity rather than 'collaboration tools'?

Should we aldo note...
something of the importune of these tools as a very giving access and accommodations to people with cognitive disabilities. Gives the "a seat at the table".
Real time collaboration functionality is maybe one of the most powerful tools for cognitive accessibility. Helping someone in real-time finding their place, tracking information, giving real time understanding. Real time editing can serve functional cognitive assistance can be under the guise of ‘collaboration’. Think about screen sharing with a family member to help them complete a process? Or end bling someone in vocational capacity that needs assistance for access.

**Comment by jasonjgw** [comment]
Section 1 already characterizes what we mean by "collaboration tool" for purposes of this document. In general, we do not mention proprietary products by name in W3C publications.

We could, if desired, add text that excludes real-time communication features and refers to RAUR. Is there anything else we could or should do here?

**Comment by sehollier** [comment]
My feeling is that this document is specifically about "Content collaboration" tools, where other collaboration tools can wonder into social media territory or remote/RTC territory.

**Comment by JaninaSajka** [comment]
Accepted. RQTF thanks COGA for helping us clarify the scope of this document.
