### ISSUE TITLE
Facilitating review of comments in collaborative content.

### ISSUE THREAD

**Issue by jasonjgw** [w3c/ctaur#26]
[Quoting the COGA Task Force comment as submitted to the mailing list]:

We had great difficulty following threads in comments and mentally following were these multiple discussions ended and what the conclusion was, as well as the overall status of the document.
This could lead to a requirement of allowing wrapp features on any text and expanding any section of the screen so that full text is visible.

**Comment by jasonjgw** [comment]
How is this distinct from WCAG reflow requirements?

**Comment by sehollier** [comment]
Agreed, it seems to be reflow to me.

**Comment by JaninaSajka** [comment]
RQTF believes we have resolved both the underlying reflow concern in our document text, but also our communications glitches with COGA about this and other concerns.
