### ISSUE TITLE
Coga Suggested Edit: Add reference to people with cognitive disabilities to existing REQ 3

### ISSUE THREAD

**Issue by davidofyork** [w3c/ctaur#41]
Add the following text to the end of REQ 3: 
_People with cognitive disabilities and attention-related impairments can also lose their train of thought and orientation due to interruptions from messages, notifications and other similar noises and distractions._

Comment from COGA Task Force.

**Comment by JaninaSajka** [comment]
Accepted and added COGA to the User Need, but the explanatory statement is rejected as we also aren't explaining why AT users have this need.
