### ISSUE TITLE
 in-page instructions

### ISSUE THREAD

**Issue by lseeman** [w3c/ctaur#74]
Add the following user need and requirements 
Suggested User need  21: As a user who finds some web sites hard to use and struggles with remembering and following instructions, I sometimes need in-page instructions so that I can do the correct task.
REQ (requirement/pattern) 21 A: Instructions from the document owner can be placed in a reserved consistent location that is easy to find. 
REQ (requirement/pattern) 21 B: Context sensitive help is available for tasks, workflow and any non-standard elements and support information for screen reader capabilities.

**Comment by JaninaSajka** [comment]
RQTF suggests this observation is more appropriately filed against WCAG Understanding, specifically against [Guideline 3.2: Predictable](https://www.w3.org/WAI/WCAG21/Understanding/predictable.html#main) perhaps to clarify that on screen positioning consistency is similarly important to navigation ordering.
