### ISSUE TITLE
requirements 5 would be confusing rather than helpful

### ISSUE THREAD

**Issue by lseeman** [w3c/ctaur#75]
We have problems with requirements for user need  5: as we feel the requirements suggested would be confusing rather than helpful. For REQ 5A, I would turn it off and then forget to turn it on again and work on an old version.
For REQ 5B  Personally, I would reload the document as I would assume it was just not working well

original Text follows:
User Need 5: Users with vision, cognitive or physical disabilities need to be able to edit content without the distraction of changes introduced by collaborators.
REQ (requirement/pattern) 5A: Provide a mode of operation in which changes made by collaborators are not displayed while the user is editing, or
REQ (requirement/pattern) 5B: Provide a mode of operation in which the component of the content that the user is editing (e.g., the paragraph, section, semantic unit of source code, or graphical object) can only be changed by one collaborator at a time, preventing others from making simultaneous modifications to the same component.

Suggestion 
remove...

**Comment by JaninaSajka** [comment]
We consider this requirement far too important to remove so we have further annotated it to require some kind of status indicator be present.
