### ISSUE TITLE
suggestion to add to add coga to user need 11 

### ISSUE THREAD

**Issue by lseeman** [w3c/ctaur#78]
suggestion to add to user need 11 - version control 

Original text: ) Assistive technology users need to be able to read the text with information included about suggested changes (i.e., insertions, deletions or formatting modifications proposed by collaborators).

Suggestion: add that people with cognitive disabilities also need to

- see these changes, 
- hide the changes, and 
- easily get the latest clean version

**Comment by JaninaSajka** [comment]
Removed the specific reference to AT and changed 'user' to 'collaborators' to denote that everyone needs this data.
