### ISSUE TITLE
short meaningful subjects 

### ISSUE THREAD

**Issue by lseeman** [w3c/ctaur#83]
Original text: REQ (requirement/pattern) 16B: If e-mail or a similar medium is used to deliver notifications, ensure that the subject of the message clearly specifies the project, document or issue relevant to the notification. 

We do not like this requirement  at all. do not create a wall of text before giving us the label that means something to us. that is not a document name!

For example I get many emails like  “issue github 1073 has been changed”.
Or ”the document revving cogas comments as a new comment”.
Assume I can only open 10 of these and assume I get 60. How do I know what to open? If one is important, but I can not deal with it now, how will I find it again? 

Compair with a subject line like “assistive technology and coga -github issue by phill jenkins, has a new comment from city mouse” This is trackable and understandable. Here, the first thing is the meaningful label. 

Suggestion, make short meaningful subjects that summarize the main point in the message and not the document name or auto generated tags that can apply to multiple messages. The subject / label/ header need to change when new issues or topics start to get discussed so I can find the new topic.

**Comment by JaninaSajka** [comment]
Added the world 'title' to clarify we're looking for text, not just numerical references.
