### ISSUE TITLE
Replace the word “to learn” with “familiar with”.

### ISSUE THREAD

**Issue by lseeman** [w3c/ctaur#85]
Original text: User Need 19: Users with learning or cognitive disabilities or who use assistive technologies need to be able to learn collaboration tools efficiently, including software with which they are unfamiliar and which is necessary to the task at hand.

Suggestion: Replace the word “to learn” with “familiar with”. Learning is often impossible such as with early stage dementia as MCI. With a familiar interface learning is not net needed!

**Comment by JaninaSajka** [comment]
Addressed by shortening the userneed description.
