### ISSUE TITLE
allow users to roll back to an older interface 

### ISSUE THREAD

**Issue by lseeman** [w3c/ctaur#86]
REQ (requirement/pattern) 19 D:  When new processes or designs are added, keep them as familiar to the user as possible. Allow users to roll back to an older interface where they exist. This allows older users to continue being productive.

**Comment by JaninaSajka** [comment]
We infer the actual problem is loss of functionality on a software version upgrade, but there's no explanation of what may be unique to collaborative software in such circumstances.
