### ISSUE TITLE
Add the term “ familiar terms “

### ISSUE THREAD

**Issue by lseeman** [w3c/ctaur#87]
Original text: REQ (requirement/pattern) 19A: In implementing collaboration features, follow established user interface conventions and design patterns. For example, use conventional terminology, labels, or icons for functionality that may be familiar to users.
For example a person with MCI may be unable to learn new infaces but can retain old skills and knowledge. 

Suggestion: Add the term “ familiar terms “ to the requirement . as : 

REQ (requirement/pattern) 19A: In implementing collaboration features, follow established user interface conventions, familiar terms,  and familiar design patterns

**Comment by JaninaSajka** [comment]
This request would make our text redundant. 'Conventional terminology' for reasons of familiarity is addressed in the following sentence!
