### ISSUE TITLE
messaging November 2022

### ISSUE THREAD

**Issue by shawna-slh** [w3c/ctaur#9]
* [x] tweet &mdash; options for a more engaging tweet at https://github.com/w3c/ctaur/blob/shawna-slh-tweet/messaging/6.tweet.md Any comments or preferences?
* [x] W3C news &mdash; [draft](https://github.com/w3c/ctaur/blob/main/messaging/3.w3c-news.md) is too long for this type of publication. Please see other [W3C news](https://www.w3.org/blog/news/) and [W3C news headlines and template](https://www.w3.org/WAI/cc/wiki/WAI_Announcement_Drafts#W3C_News_-_XYZ):
> The XYZ Working Group ([XWG](https://@@/)) has published a First Public Working Draft of [Spec](https://@@/). Couple-few sentences about it. Comments are welcome through 00 Month 2019.
* [x] WAI news &mdash; https://github.com/w3c/wai-news/blob/master/_posts/2022-11-08-ctaur.md
* [x] email &mdash; We use plain text. A few tweaks are needed to [e-mail draft](https://github.com/w3c/ctaur/blob/shawna-slh-tweet/messaging/2.wai-e-mail.md)

**Comment by ruoxiran** [comment]
hi, Shawn, I have updated W3C news, please see [W3C news](https://www.w3.org/blog/news/), please feel   free to tweet.

**Comment by matatk** [comment]
For the tweet, @JaninaSajka, @ruoxiran and I prefer option 1; thanks :-).

**Comment by matatk** [comment]
@shawna-slh: I updated the format of the email to plain text, but kept the .md extension, so links won't break. Note: I didn't include the tweet text verbatim.

@JaninaSajka, @ruoxiran, and I propose that, in future, we could commit the email announcement files as plain text (with a .txt extension) so as to ensure the right format is used. Is that OK with you?

Oops: I updated it in `main` first because I didn't notice the link was to your branch; I have updated it in your branch too now.

**Comment by shawna-slh** [comment]
Yes, please do use plain text for the email. That will be easier on all of us!

I made several tweaks. Given the timing, I just sent the messages rather than run them through a review cycle. I hope that's OK! 

Changes to the e-mail include:
* added a link to the draft :-)
* passive voice -> active voice in the comment section
* simpler sentence structure
* fixed punctuation (I hope!) "... unique to interactive, collaborative, content creation and editing applications" -> "... unique to interactive, collaborative content creation and editing applications"
* edited wording about COGA to be more publicly friendly (I hope :-)
* "Task Force Facilitators." -> "Research Questions Task Force (RQTF) Facilitators"
* "APA Working Group" -> "Accessible Platform Architectures (APA) Working Group"

[diff](https://github.com/w3c/ctaur/pull/8/files)

fyi to @ruoxiran @matatk 

<hr>

I also deleted this sentence:
> The accessibility issues raised by these capabilities are not directly addressed elsewhere in W3C’s guidance.

If we want to say something like that, I'd like us to think a bit about a slightly different approach that doesn't lend itself to being misconstrued to "WCAG doesn't cover these tools". Maybe along the lines of: This document addresses issues more specifically than is covered in W3C's existing guidance.  ?

**Comment by ruoxiran** [comment]
thanks, Shawn！

**Comment by ruoxiran** [comment]
> @JaninaSajka, @ruoxiran, and I propose that, in future, we could commit the email announcement files as plain text (with a .txt extension) so as to ensure the right format is used. Is that OK with you?

OK with me, let add this topic to our plan call. thanks.

**Comment by danarose123** [comment]
> For the tweet, @JaninaSajka, @ruoxiran and I prefer option 1; thanks :-).
